version: 2

updates:
- package-ecosystem: composer
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: 'Composer:'

- package-ecosystem: docker
  directories:
  - /.docker/app
  - /.docker/web-nginx
  schedule:
    interval: weekly
  commit-message:
    prefix: 'Docker:'

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: 'GitHub Actions:'
