name: Bug Report
description: Report a bug
labels: [bug]

body:
- type: textarea
  id: problem
  attributes:
    label: What is the problem?
  validations:
    required: true

- type: textarea
  id: reproduction
  attributes:
    label: Reproduction Steps
    description: (If known) Minimal steps that can reproduce the issue.
  validations:
    required: false

- type: input
  id: version
  attributes:
    label: tt-rss Version
    description: Which version (commit) of tt-rss are you using?
  validations:
    required: true

- type: textarea
  id: environment
  attributes:
    label: Environment
    description: |
      How are you running tt-rss?  Include all relevant details (e.g. Docker image, OS, PHP version, etc.).
  validations:
    required: true

- type: textarea
  id: other
  attributes:
    label: Other Information
    description: |
      Anything else you want to provide (e.g. related issues, suggestions on how to fix, links for context, etc.).
  validations:
    required: false

- type: checkboxes
  id: acknowledgments
  attributes:
    label: Acknowledge
    description: Please mark any checkbox that applies (otherwise leave unchecked).
    options:
      - label: I'm interested in implementing the fix
        required: false
