name: Documentation Issue
description: Report an issue with documentation
labels: [documentation]

body:
- type: textarea
  id: issue
  attributes:
    label: What is the issue?
  validations:
    required: true
