name: Documentation Issue
description: Report an issue with documentation
labels: [documentation]

body:
- type: textarea
  id: issue
  attributes:
    label: What is the issue?
  validations:
    required: true

- type: checkboxes
  id: acknowledgments
  attributes:
    label: Acknowledge
    description: Please mark any checkbox that apply (otherwise leave unchecked).
    options:
    - label: I'm interested in implementing the fix
      required: false
